### ISSUE TITLE
Decimal Precision Issue

### ISSUE THREAD

**Issue by genxcoders** [trendoman/Cms-Fu#1]
Hi!
There is an issue that I encountered.
When using the inr-format function it works well for decimal_precision set upto 3 decimal places. The moment a 4th decimal place is added the output generated is wrong.

For Example:
```
<cms:func 'inr-format' val=''>
   <cms:php>
      global $CTX;
      $val = str_replace( array(',', ' '), '', $CTX->get('val'));
      $CTX->set('val', $val, 'parent');
   </cms:php>
   <cms:set val = "<cms:number_format number=val decimal_character='.' thousands_separator='' decimal_precision='2' />" />
   <cms:php>
      echo '₹ ', $num = preg_replace("/(\d+?)(?=(\d\d)+(\d)(?!\d))(\.\d+)?/i", "$1,", '<cms:show val />');
   </cms:php>
</cms:func>

<cms:call 'inr-format' '123456.0527' />
```

Expected Output: 1,23,456.0527
Generated Output: 1,23,456.0,527

There should be no comma in the values after the decimal point in any place value system. Also, I suppose the INR symbol should be removed from the func as it limits the usage to INR. The currency symbol, if needed, can be added by designer/ developer. If the number being output is that of the available quantity of water in a 15Million liter water tank, then the INR symbol will change its meaning entirely.

I was trying to generate a PR but it didnt happen hence I am posting it as an issue here.

**Comment by trendoman** [comment]
Thanks for the head's up. Will address those issues shortly!

**Comment by trendoman** [comment]
@genxcoders I am having the output trimmed to 2 decimals after the dot, due to **decimal_precision** set to *2*, e.g. my result is `1,23,456.05`. Did you change that parameter to *4* in func's code? That can explain your outcome. Please confirm, if you think there must be values with more than 2 digits after the dot.
